Repository YunoHost-Apps/wallabag2_ynh, pull requests merged in 2022-07, with the labels that each got.

#134 Upgrade to 2.5
  README.md
  README_fr.md
  conf/app.src
  manifest.json
Labels: enhancement, help wanted, pending

#142 Fix PHP dependencies (fixes #140)
  scripts/_common.sh
Labels: help wanted

#139 Testing : upgrade to 2.5 / fix php dependencies
  README.md
  README_fr.md
  conf/app.src
  manifest.json
  scripts/_common.sh
Labels: bug, enhancement

#145 fix php7.4-redis conflicting with php-redis
  scripts/_common.sh
Labels: bug
